// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAn-XH9dZuhUsMD8NmNsaD9C7-asou3pTY',
    appId: '1:183285935046:web:412cca91c75907fc4fe0c7',
    messagingSenderId: '183285935046',
    projectId: 'social-app-3366e',
    authDomain: 'social-app-3366e.firebaseapp.com',
    storageBucket: 'social-app-3366e.appspot.com',
    measurementId: 'G-087570KCK7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVz_ZX2C8_oDOsgPRDpXzXQ6oX9dWND2w',
    appId: '1:183285935046:android:8832482356f7b1f84fe0c7',
    messagingSenderId: '183285935046',
    projectId: 'social-app-3366e',
    storageBucket: 'social-app-3366e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9DrWqgRu6PrnW_1jtTbkE_DjtFBQzglo',
    appId: '1:183285935046:ios:d6af2d9fb4a6f8ce4fe0c7',
    messagingSenderId: '183285935046',
    projectId: 'social-app-3366e',
    storageBucket: 'social-app-3366e.appspot.com',
    iosBundleId: 'com.example.socialApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9DrWqgRu6PrnW_1jtTbkE_DjtFBQzglo',
    appId: '1:183285935046:ios:897b661fbf3c67964fe0c7',
    messagingSenderId: '183285935046',
    projectId: 'social-app-3366e',
    storageBucket: 'social-app-3366e.appspot.com',
    iosBundleId: 'com.example.socialApp.RunnerTests',
  );
}
